name: Smoke Test

on:
  # On pull requests to main
  pull_request:
    branches:
      - main
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

jobs:
  validate-podspec:
    runs-on: macos-latest
    steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '16.0' # Meta Audience Network requires Xcode 16.0 starting in version 6.16.0

      - name: Adapter smoke test
        uses: chartboost/chartboost-mediation-ios-actions/adapter-smoke-test@v1
        with:
          allow-warnings: true